### ISSUE TITLE
Removal of Phys thing doesn't work in Update Project Collection workflow

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-for-science#1232] opened 2023-07-27 21:00 UTC
To reproduce:

Add several Physical Things to a Project in the New Project Workflow. 
Then start the Update Project Collection Workflow. 
Remove one or more physical things.
Observe in the Summary Step that the list of Physical Things shows the original number of things. 
Restart the workflow and notice that nothing has been removed.

![Image](https://user-images.githubusercontent.com/1877663/256662890-3a1319a0-0961-4919-a47a-a06a7fcc9312.png)

![Image](https://user-images.githubusercontent.com/1877663/256662806-fe8a3e95-0729-4319-aa85-9a7f09d4a60f.png)

**Comment by jacobtylerwalls** [comment] 2023-08-02 13:52
@chiatt I can't reproduce the issue as described--the deletions work for me.

However, I noticed that in the Update Collection workflow, the state of the right-side sidebar always begins empty, regardless of the number of selected physical things at the start. Is that something to be fixed (if yes, here or in a separate issue?)

<img width="1266" alt="Screenshot 2023-08-02 at 9 51 47 AM" src="https://github.com/archesproject/arches-for-science-prj/assets/38668450/95b31ba3-25a5-432f-a3c8-418baf30a599">

**Comment by jacobtylerwalls** [comment] 2023-08-02 17:44
> However, I noticed that in the Update Collection workflow, the state of the right-side sidebar always begins empty

Never mind, I had #1239 checked out, and that's a regression on that branch that I'm now looking into.

**Comment by jacobtylerwalls** [comment] 2023-09-19 22:11
Hey @njkim, I wanted to let you know that #1314 is turning out to be a pretty invasive fix, so I would suggest holding off on retesting this ticket until that work is ready for a look. (I'll request you to review it!)

**Comment by jacobtylerwalls** [comment] 2023-09-21 16:31
Fixed in #1319

**Comment by jacobtylerwalls** [comment] 2023-09-25 14:54
Fixed in #1327

**Closed by jacobtylerwalls** 2023-09-25 14:54 UTC
Labels: bug
